model:
  backbone: convnext_large
  patch_count: 2
  pretrained: true
train:
  epochs: 30
  batch_size: 8
  lr: 3e-4
  optimizer: adamw
  scheduler: cosine
  image_size: 1024
data:
  data_root: "/content/drive/MyDrive/Projects/CSIRO_I2B/Dataset"
  augment:
    color_jitter: true
    horizontal_flip: true
loss:
  type: smooth_l1
experiment:
  save_dir: "./experiments"
